
import React from "react"; 

import './CompanyInfoSection.css'

function CompanyInfoSection(props) {
    return (
        <div className='info'>
            <p>Chameleon aims to utilise the Internet of Things (IoT), which is an ecosystem consisting of web-enabled smart devices such as phones, suburban traffic systems and domestic appliances, that all use embedded systems, such as processors, sensors, and communication hardware, to collect, send and act on data they acquire from their environments. </p>
            <p>We hope to harness the data generated by these systems through researching, creating, testing, documenting and deploying IoT-based solutions which aim to enhance life through the application of smart city technologies including: the building of smarter cities, homes, transportation, and energy management systems.</p>
            <p>If you would like to learn more about what this looks like in practice, navigate to our Portfolio section!</p>
        </div>
    )
}

export default CompanyInfoSection;

